import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import axiosInstance from '../axiosConfig';

// Frontend for user (freelance) project panel
// Implement and test Add/Create method functionality (Jira FPM-4)
// Implement and test View/Get method functionality (Jira FPM-10)
// Implement and test Update method functionality (Jira FPM-14)
// Implement and test Delete method functionality (Jira FPM-18)

// Chain of Responsibility Integration
// Displays validation errors generated by:
// - TitleValidationHandler
// - BudgetValidationHandler
// - DeadlineValidationHandler
// in the frontend project form.

const ProjectForm = ({
  projects,
  setProjects,
  editingProject,
  setEditingProject
}) => {

  const { user } = useAuth();

  // Form state used for project create/update
  const [formData, setFormData] = useState({
    title: '',
    clientName: '',
    description: '',
    budget: '',
    status: 'Pending',
    deadline: ''
  });

  // Stores validation errors returned from the
  // Chain of Responsibility handlers in the backend
  const [error, setError] = useState('');

  useEffect(() => {

    // Clear previous validation messages whenever
    // user switches project or exits edit mode
    setError('');

    if (editingProject) {

      setFormData({
        title: editingProject.title,
        clientName: editingProject.clientName,
        description: editingProject.description,
        budget: editingProject.budget,
        status: editingProject.status,
        deadline: editingProject.deadline,
      });

    } else {

      setFormData({
        title: '',
        clientName: '',
        description: '',
        budget: '',
        status: 'Pending',
        deadline: ''
      });

    }

  }, [editingProject]);

  const handleSubmit = async (e) => {

    e.preventDefault();

    // Clear any previous validation errors
    setError('');

    try {

      if (editingProject) {

        const response = await axiosInstance.put(
          `/api/projects/${editingProject._id}`,
          formData,
          {
            headers: {
              Authorization: `Bearer ${user.token}`
            }
          }
        );

        setProjects(
          projects.map((project) =>
            project._id === response.data._id
              ? response.data
              : project
          )
        );

      } else {

        const response = await axiosInstance.post(
          '/api/projects',
          formData,
          {
            headers: {
              Authorization: `Bearer ${user.token}`
            }
          }
        );

        setProjects([
          ...projects,
          response.data
        ]);

      }

      // Clear form after successful save
      setEditingProject(null);

      setFormData({
        title: '',
        clientName: '',
        description: '',
        budget: '',
        status: 'Pending',
        deadline: ''
      });

    } catch (error) {

      // Extract backend validation message from
      // Chain of Responsibility handlers
      const errorMessage =
        error.response?.data?.message ||
        'Failed to save project.';

      // Show message inside form
      setError(errorMessage);

      // Also show popup for demonstration/testing
      alert(errorMessage);

    }

  };

  return (

    <form
      onSubmit={handleSubmit}
      className="bg-white p-6 shadow-md rounded mb-6"
    >

      <h1 className="text-2xl font-bold mb-4">
        {editingProject
          ? 'Edit Project'
          : 'Add Project'}
      </h1>

      {/* Display validation messages returned by the
          Chain of Responsibility validation handlers */}
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
          {error}
        </div>
      )}

      <input
        type="text"
        placeholder="Project Title"
        value={formData.title}
        onChange={(e) =>
          setFormData({
            ...formData,
            title: e.target.value
          })
        }
        className="w-full mb-4 p-2 border rounded"
      />

      <input
        type="text"
        placeholder="Client Name"
        value={formData.clientName}
        onChange={(e) =>
          setFormData({
            ...formData,
            clientName: e.target.value
          })
        }
        className="w-full mb-4 p-2 border rounded"
      />

      <input
        type="text"
        placeholder="Description"
        value={formData.description}
        onChange={(e) =>
          setFormData({
            ...formData,
            description: e.target.value
          })
        }
        className="w-full mb-4 p-2 border rounded"
      />

      <input
        type="number"
        placeholder="Budget"
        value={formData.budget}
        onChange={(e) =>
          setFormData({
            ...formData,
            budget: e.target.value
          })
        }
        className="w-full mb-4 p-2 border rounded"
      />

      <select
        value={formData.status}
        onChange={(e) =>
          setFormData({
            ...formData,
            status: e.target.value
          })
        }
        className="w-full mb-4 p-2 border rounded"
      >
        <option value="Pending">
          Pending
        </option>

        <option value="In Progress">
          In Progress
        </option>

        <option value="Completed">
          Completed
        </option>
      </select>

      <input
        type="date"
        value={formData.deadline}
        onChange={(e) =>
          setFormData({
            ...formData,
            deadline: e.target.value
          })
        }
        className="w-full mb-4 p-2 border rounded"
      />

      <button
        type="submit"
        className="w-full bg-blue-600 text-white p-2 rounded"
      >
        {editingProject
          ? 'Update Project'
          : 'Add Project'}
      </button>

    </form>

  );
};

export default ProjectForm;